#Quinoa
quarkus.quinoa.package-manager-install.node-version=20.20.0
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.ui-root-path=quinoa
quarkus.quinoa.enable-spa-routing=true

#Database
# ===== DEV =====
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_db
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=postgres
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# ===== PROD =====
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_db
%prod.quarkus.datasource.username=postgres
%prod.quarkus.datasource.password=postgres
%prod.quarkus.hibernate-orm.schema-management.strategy=validate

# ===== TEST =====
%test.quarkus.datasource.enabled=false
%test.quarkus.hibernate-orm.enabled=false
%test.quarkus.devservices.enabled=false

#Smallrye-openapi
quarkus.smallrye-openapi.info-title=Holiday API
quarkus.smallrye-openapi.store-schema-directory=src/main/webui/
quarkus.swagger-ui.always-include=true