---
openapi: 3.1.0
paths:
  /api/holidays:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/HolidayDTO"
      summary: Get Holidays
      tags:
      - Holiday Resource
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HolidayDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HolidayDTO"
        "400":
          description: Bad Request
      summary: Create Holiday
      tags:
      - Holiday Resource
  /api/holidays/{id}:
    put:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HolidayDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HolidayDTO"
        "400":
          description: Bad Request
      summary: Update Holiday
      tags:
      - Holiday Resource
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
      summary: Remove
      tags:
      - Holiday Resource
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HolidayDTO"
      summary: Get Holiday
      tags:
      - Holiday Resource
  /hello:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Hello
      tags:
      - Greeting Resource
components:
  schemas:
    HolidayDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        coverPath:
          type: boolean
info:
  title: Holiday API
  version: 1.0.0-SNAPSHOT
servers:
- url: http://localhost:8080
  description: Auto generated value
- url: http://0.0.0.0:8080
  description: Auto generated value
